POST http://localhost:5001/seed/user
Content-Type: application/json

POST http://localhost:5001/seed/course
Content-Type: application/json

GET http://localhost:5001/testt
### Auth

## Signup
POST http://localhost:5001/api/signup
Content-Type: application/json

{
    "email": "hoQWJUYE21qw3XFGFgmail.com",
    "password": "12345678"
}

## Login
POST http://localhost:5001/api/signin
Content-Type: application/json

{
    "email": "hoismail1430@gmail.com",
    "password": "12345678"
}


## Verify OTP for login
POST http://localhost:5001/api/verify?email=hoismail1430@gmail.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODgwNDAwMzAsImV4cCI6MTY4ODA0MTgzMH0.upNdglUhSOqmwnMbROdYrPZWNazdp_fRW1AN4EGS3GA

{
    "otp": "297624"
}


### ADMIN

## Create course
POST http://localhost:5001/api/course
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImZpcnN0TmFtZSI6Ikh1ZGhheWZhaCIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiY291cnNlSUQiOiI2NGE5ODNmNmVhMDcwMDM1NzllYzI2ODAiLCJfaWQiOiI2NDk5N2Y2YTBjZjhjMzNjNzczYzIyNWMifSx7ImNvdXJzZUlEIjoiNjRhOTgzZjdlYTA3MDAzNTc5ZWMyNjg0IiwicHJvZ3Jlc3MiOiJOb3Qtc3RhcnRlZCIsIl9pZCI6IjY0ZGEzNzlkOGY1YzU0Zjg2N2I2OWM2YyJ9LHsiY291cnNlSUQiOiI2NGE5ODNmN2VhMDcwMDM1NzllYzI2ODQiLCJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiX2lkIjoiNjRkYTM3Zjk4ZjVjNTRmODY3YjY5YzcxIn1dLCJpYXQiOjE3MDU1OTQzNzMsImV4cCI6MTcwNTY4MDc3M30.FHqDsXz2lut6bBacLEWB_tuI47ZA4h_v23d8rDZb2uA

{
    "name": "Traning1",
    "description": "Testing",
    "courseType": "free"
}

## Created course
GET http://localhost:5001/created-courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbXSwiaWF0IjoxNjg3NzgwNTExLCJleHAiOjE2ODgwMzk3MTF9.BPVqq1aroSqHA3pPhd2uxnXKRM9aYc07n1DgzY3kzWI

## Assign Instructors
PATCH http://localhost:5001/api/course/649d2721e16c05d7bee1ce98/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODgwNDIxMzQsImV4cCI6MTY4ODMwMTMzNH0.ByLcqrYVFtaBRCPFAvjG7ecMehh_2X8Z8yGPyLQOkds
# 649c6c4774f92d779a188018
{
    "instructors": ["649f6feeb918d417dc4eeef2"]
}

## Set course status
PUT http://localhost:5001/api/course/65ae9a802936f37ee3cc5fd1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImZpcnN0TmFtZSI6Ikh1ZGhheWZhaCIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJwcm9ncmVzcyI6Im5vdC1zdGFydGVkIiwiY291cnNlSUQiOiI2NGE5ODNmNmVhMDcwMDM1NzllYzI2ODAiLCJfaWQiOiI2NDk5N2Y2YTBjZjhjMzNjNzczYzIyNWMifSx7ImNvdXJzZUlEIjoiNjRhOTgzZjdlYTA3MDAzNTc5ZWMyNjg0IiwicHJvZ3Jlc3MiOiJOb3Qtc3RhcnRlZCIsIl9pZCI6IjY0ZGEzNzlkOGY1YzU0Zjg2N2I2OWM2YyJ9LHsiY291cnNlSUQiOiI2NGE5ODNmN2VhMDcwMDM1NzllYzI2ODQiLCJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiX2lkIjoiNjRkYTM3Zjk4ZjVjNTRmODY3YjY5YzcxIn0seyJjb3Vyc2VJRCI6IjY1YTk4NzcwMGEzMjgzNjc3NDI1ZDIzZiIsInByb2dyZXNzIjoibm90LXN0YXJ0ZWQiLCJfaWQiOiI2NWE5ODgzYTBhMzI4MzY3NzQyNWQyNDYifV0sImlhdCI6MTcwNTk0MTYxMiwiZXhwIjoxNzA2MDI4MDEyfQ.rSnrubtpS94uAVFAY4HC0rSWayeZp2mUdjsx4l03wBM
# 649c6c4774f92d779a188018
{
    "status": "application",
    "deadline": "2024-02-05T00:00:00.000Z"
}

## View tthe list of all users
GET http://localhost:5001/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODg2NTI1NjQsImV4cCI6MTY4ODY1NDM2NH0.kXMwzlCEXCje6MMgaO2UMgVIQ2kDruYXDWq5d01cyLk

## View user details
GET http://localhost:5001/api/user/649c6c4774f92d779a188018
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODgwNDIxMzQsImV4cCI6MTY4ODMwMTMzNH0.ByLcqrYVFtaBRCPFAvjG7ecMehh_2X8Z8yGPyLQOkds

## Get all instructors
GET http://localhost:5001/api/instructors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODg2NTg4NzMsImV4cCI6MTY4ODkxODA3M30.9dNJ0SdrRcoekrv5h0fUydnPOacB2FY7zFRd61PQ-Xk

## View a particular instructor
GET http://localhost:5001/api/instructor/649c6c4774f92d779a188018
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODgwNDIxMzQsImV4cCI6MTY4ODMwMTMzNH0.ByLcqrYVFtaBRCPFAvjG7ecMehh_2X8Z8yGPyLQOkds

## Deassign instructor
PATCH http://localhost:5001/api/instructor/649c6bfc74f92d779a188016/deassign/course/649d2721e16c05d7bee1ce98
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODgwNDIxMzQsImV4cCI6MTY4ODMwMTMzNH0.ByLcqrYVFtaBRCPFAvjG7ecMehh_2X8Z8yGPyLQOkds

## Delete user account
DELETE http://localhost:5001/api/user/649c6c4774f92d779a188018/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODgwNDIxMzQsImV4cCI6MTY4ODMwMTMzNH0.ByLcqrYVFtaBRCPFAvjG7ecMehh_2X8Z8yGPyLQOkds
### NOot loggedIn
### BOTH

## All courses
GET http://localhost:5001/api/courses
Content-Type: application/json



## View a course
GET http://localhost:5001/api/course/65a1092ba2961ea4252c2e63
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImZpcnN0TmFtZSI6Ikh1ZGhheWZhaCIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiY291cnNlSUQiOiI2NGE5ODNmNmVhMDcwMDM1NzllYzI2ODAiLCJfaWQiOiI2NDk5N2Y2YTBjZjhjMzNjNzczYzIyNWMifSx7ImNvdXJzZUlEIjoiNjRhOTgzZjdlYTA3MDAzNTc5ZWMyNjg0IiwicHJvZ3Jlc3MiOiJOb3Qtc3RhcnRlZCIsIl9pZCI6IjY0ZGEzNzlkOGY1YzU0Zjg2N2I2OWM2YyJ9LHsiY291cnNlSUQiOiI2NGE5ODNmN2VhMDcwMDM1NzllYzI2ODQiLCJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiX2lkIjoiNjRkYTM3Zjk4ZjVjNTRmODY3YjY5YzcxIn1dLCJpYXQiOjE3MDU1OTQzNzMsImV4cCI6MTcwNTY4MDc3M30.FHqDsXz2lut6bBacLEWB_tuI47ZA4h_v23d8rDZb2uA

## Contact
POST http://localhost:5001/api/message
Content-Type: application/json

{
    "name": "Test",
    "email": "hoismail1430@gmail.com",
    "message": "Testing"
}

### USER
## Registered courses
GET http://localhost:5001/api/mycourses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJjb3Vyc2VJRCI6IjY0OTk3NDY2NThiYmMwMGJhYWE1NzJjMyIsIl9pZCI6IjY0OTk3ZjZhMGNmOGMzM2M3NzNjMjI1YyJ9LHsiY291cnNlSUQiOiI2NDlkMjcyMWUxNmMwNWQ3YmVlMWNlOTgiLCJfaWQiOiI2NDlkM2IzNzNlMWQwZWVhYjgwMzY3NDMifSx7ImNvdXJzZUlEIjoiNjQ5ZDI3MjFlMTZjMDVkN2JlZTFjZTk4IiwiX2lkIjoiNjQ5ZDNiYjM1OWEyY2VkYmZlMzNiNWM2In1dLCJpYXQiOjE2ODg2NTg4NzMsImV4cCI6MTY4ODkxODA3M30.9dNJ0SdrRcoekrv5h0fUydnPOacB2FY7zFRd61PQ-Xk

## Register course ----- Handle to check if already registerred
POST http://localhost:5001/api/course/65a987700a3283677425d23f/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImZpcnN0TmFtZSI6Ikh1ZGhheWZhaCIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiY291cnNlSUQiOiI2NGE5ODNmNmVhMDcwMDM1NzllYzI2ODAiLCJfaWQiOiI2NDk5N2Y2YTBjZjhjMzNjNzczYzIyNWMifSx7ImNvdXJzZUlEIjoiNjRhOTgzZjdlYTA3MDAzNTc5ZWMyNjg0IiwicHJvZ3Jlc3MiOiJOb3Qtc3RhcnRlZCIsIl9pZCI6IjY0ZGEzNzlkOGY1YzU0Zjg2N2I2OWM2YyJ9LHsiY291cnNlSUQiOiI2NGE5ODNmN2VhMDcwMDM1NzllYzI2ODQiLCJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiX2lkIjoiNjRkYTM3Zjk4ZjVjNTRmODY3YjY5YzcxIn1dLCJpYXQiOjE3MDU1OTQzNzMsImV4cCI6MTcwNTY4MDc3M30.FHqDsXz2lut6bBacLEWB_tuI47ZA4h_v23d8rDZb2uA

## Assigned courses
GET http://localhost:5001/api/assigned-courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YSIsImZpcnN0TmFtZSI6ImphbmUiLCJlbWFpbCI6ImphbmVzbWl0aEBleGFtcGxlLmNvbSIsInVzZXJUeXBlIjoiaW5zdHJ1Y3RvciIsImNvdXJzZXMiOlt7ImNvdXJzZUlEIjoiNjE1ZTI5YzdhOGIxZTVlM2YyNDNlNjI1IiwicHJvZ3Jlc3MiOiJpbi1wcm9ncmVzcyIsIl9pZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YiJ9LHsiY291cnNlSUQiOiI2MTVlMjljN2E4YjFlNWUzZjI0M2U2MjciLCJwcm9ncmVzcyI6ImNvbXBsZXRlZCIsIl9pZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YyJ9XSwiaWF0IjoxNjg4OTk1NjUyLCJleHAiOjE2ODg5OTc0NTJ9.4-nEja7i3MaMl2Gkbd6M6QFhkrkSMHBrxc6g7D86rQg

POST http://localhost:5001/api/quiz/setup
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YSIsImZpcnN0TmFtZSI6ImphbmUiLCJlbWFpbCI6ImphbmVzbWl0aEBleGFtcGxlLmNvbSIsInVzZXJUeXBlIjoiaW5zdHJ1Y3RvciIsImNvdXJzZXMiOlt7ImNvdXJzZUlEIjoiNjE1ZTI5YzdhOGIxZTVlM2YyNDNlNjI1IiwicHJvZ3Jlc3MiOiJpbi1wcm9ncmVzcyIsIl9pZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YiJ9LHsiY291cnNlSUQiOiI2MTVlMjljN2E4YjFlNWUzZjI0M2U2MjciLCJwcm9ncmVzcyI6ImNvbXBsZXRlZCIsIl9pZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YyJ9XSwiaWF0IjoxNjg4OTk1NjUyLCJleHAiOjE2ODg5OTc0NTJ9.4-nEja7i3MaMl2Gkbd6M6QFhkrkSMHBrxc6g7D86rQg

{
    "name": "Basic",
    "link": "https://docs.google.com/forms/d/e/1FAIpQLSci38XX3QqSKIY0PkfYWME7MV8RFvBFFwmRG3tTQwvbvBzF4w/viewform",
    "sheetID": "1NdJOgtlq030C__p5_8gJjjXLG12R_DBB_AHq-R9ChN0"
}

POST http://localhost:5001/api/quiz/Basic/1NdJOgtlq030C__p5_8gJjjXLG12R_DBB_AHq-R9ChN0/completed/proceed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0OTgzYmU5ODk2Yzc4YzI3OWM4ZDlmYSIsImZpcnN0TmFtZSI6Ikh1ZGhheWZhaCIsImVtYWlsIjoiaG9pc21haWwxNDMwQGdtYWlsLmNvbSIsInVzZXJUeXBlIjoiYWRtaW4iLCJjb3Vyc2VzIjpbeyJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiY291cnNlSUQiOiI2NGE5ODNmNmVhMDcwMDM1NzllYzI2ODAiLCJfaWQiOiI2NDk5N2Y2YTBjZjhjMzNjNzczYzIyNWMifSx7ImNvdXJzZUlEIjoiNjRhOTgzZjdlYTA3MDAzNTc5ZWMyNjg0IiwicHJvZ3Jlc3MiOiJOb3Qtc3RhcnRlZCIsIl9pZCI6IjY0ZGEzNzlkOGY1YzU0Zjg2N2I2OWM2YyJ9LHsiY291cnNlSUQiOiI2NGE5ODNmN2VhMDcwMDM1NzllYzI2ODQiLCJwcm9ncmVzcyI6Ik5vdC1zdGFydGVkIiwiX2lkIjoiNjRkYTM3Zjk4ZjVjNTRmODY3YjY5YzcxIn1dLCJpYXQiOjE3MDU0ODE5MDcsImV4cCI6MTcwNTU2ODMwN30.EMSy39edQdH7N16Vw6S8vfIILdu6ABi7oD8ml2XtfI0


GET http://localhost:5001/api/course/64a983f7ea07003579ec2684/student/download
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YSIsImZpcnN0TmFtZSI6ImphbmUiLCJlbWFpbCI6ImphbmVzbWl0aEBleGFtcGxlLmNvbSIsInVzZXJUeXBlIjoiaW5zdHJ1Y3RvciIsImNvdXJzZXMiOlt7ImNvdXJzZUlEIjoiNjE1ZTI5YzdhOGIxZTVlM2YyNDNlNjI1IiwicHJvZ3Jlc3MiOiJpbi1wcm9ncmVzcyIsIl9pZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YiJ9LHsiY291cnNlSUQiOiI2MTVlMjljN2E4YjFlNWUzZjI0M2U2MjciLCJwcm9ncmVzcyI6ImNvbXBsZXRlZCIsIl9pZCI6IjY0YTk3YTJiNzNjZGUyOWMwMzBjZDk4YyJ9XSwiaWF0IjoxNjg4OTk1NjUyLCJleHAiOjE2ODg5OTc0NTJ9.4-nEja7i3MaMl2Gkbd6M6QFhkrkSMHBrxc6g7D86rQg

